/**
 * CustomerSegment.js
 *
 * Stores the analytical results generated by the Python ML microservice
 * after running K-Means Clustering on a Dataset's customer RFM data
 * (Recency, Frequency, Monetary value).
 *
 * Each customer is classified into one of three segments:
 *   - Premium  : High-value, frequent buyers
 *   - Regular  : Average buyers with moderate engagement
 *   - At-Risk  : Customers who haven't purchased recently
 *
 * These results power the customer segmentation dashboard and drive
 * the plain-English insights shown to business owners.
 *
 * Relationships:
 *   Dataset (1) ──generates──> (N) CustomerSegment
 */

const mongoose = require('mongoose');

const customerSegmentSchema = new mongoose.Schema(
  {
    dataset_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Dataset',
      required: true,
    },
    customer_id: {
      type: String,
      required: true,
    },
    segment_name: {
      type: String,
      enum: ['Premium', 'Regular', 'At-Risk'],
      required: true,
    },
    cluster_label: {
      type: Number, // Raw cluster index from K-Means (0, 1, 2)
      required: true,
    },
    // RFM scores used for clustering
    recency_score: {
      type: Number,
      default: 0,
    },
    frequency_score: {
      type: Number,
      default: 0,
    },
    monetary_score: {
      type: Number,
      default: 0,
    },
    // Composite score for ranking
    score: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

customerSegmentSchema.index({ dataset_id: 1 });
customerSegmentSchema.index({ dataset_id: 1, segment_name: 1 });

module.exports = mongoose.model('CustomerSegment', customerSegmentSchema);
