/**
 * Forecast.js
 *
 * Stores revenue predictions for a Dataset, generated by the Python ML
 * microservice using Linear Regression and Random Forest models.
 *
 * Supports both monthly and quarterly forecasts, each with a predicted
 * revenue value and optional confidence bounds (lower/upper range).
 * This gives business owners a clear view of expected future revenue
 * without needing any data science expertise.
 *
 * Recommended for the full InsightAI experience — forecasts are what
 * make the platform actionable rather than just descriptive.
 *
 * Relationships:
 *   Dataset (1) ──generates──> (N) Forecast
 */

const mongoose = require('mongoose');

const forecastSchema = new mongoose.Schema(
  {
    dataset_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Dataset',
      required: true,
    },
    type: {
      type: String,
      enum: ['monthly', 'quarterly'],
      required: true,
    },
    date: {
      type: Date,
      required: true,
    },
    predicted_revenue: {
      type: Number,
      required: true,
    },
    lower_bound: {
      type: Number,
      default: null,
    },
    upper_bound: {
      type: Number,
      default: null,
    },
    model_used: {
      type: String,
      enum: ['linear_regression', 'random_forest'],
      default: 'linear_regression',
    },
    confidence: {
      type: Number, // e.g., 0.95
      default: null,
    },
  },
  { timestamps: true }
);

forecastSchema.index({ dataset_id: 1, type: 1 });

module.exports = mongoose.model('Forecast', forecastSchema);
